"use client";
import type { Metadata } from "next";
import RootLayout from "../layout";
import { useTheme } from "next-themes";

export const metadata: Metadata = {
  title: "@about",
  description: "Generated by @milan"
};

export default function AboutLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <section className="about">{children}</section>;
}
