import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "@project",
  description: "Generated by @milan"
};

export default function ProjectsLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <section className="projects">{children}</section>;
}
