import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "@tech",
  description: "Generated by @milan"
};

export default function TechLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <section className="tech">{children}</section>;
}
